#+TITLE: My Emacs Config
#+AUTHOR: Laurent Lejeune
#+PROPERTY: header-args:emacs-lisp :tangle yes :results silent
#+PROPERTY: header-args :tangle "~/.config/vemacs/config.el" :lexical t

* Introduction

This is my emacs configuration. It is still at a very early stage.

#+begin_src emacs-lisp :tangle "early-init.el"
;;; early-init.el -*- lexical-binding: t; -*-
(setq package-enable-at-startup nil)

;;; disable white screen flash on GUI startup
(setq default-frame-alist '(
  (background-color . "#000000")
  (ns-appearance . dark)
  (ns-transparent-titlebar . t)))

#+end_src

#+begin_src emacs-lisp
;;; config.el -*- lexical-binding: t; -*-
#+end_src

* Custom Variables

#+begin_src emacs-lisp
  (defcustom ll/use-nerd-fonts t
    "Configuration for using Nerd Fonts Symbols."
    :type 'boolean
    :group 'appearance)
#+end_src

* General User Experience

Change the yes/no prompt to y/n
#+begin_src emacs-lisp
(fset 'yes-or-no-p 'y-or-n-p)
#+end_src

* Elpaca
#+begin_src emacs-lisp
(setq elpaca-lock-file (expand-file-name "elpaca-lock.el" user-emacs-directory))
#+end_src

Install Elpaca, our package manager.

#+begin_src emacs-lisp
  (defvar elpaca-installer-version 0.12)
  (defvar elpaca-core-date '(20260814))
  (defvar elpaca-directory (expand-file-name "elpaca/" user-emacs-directory))
  (defvar elpaca-builds-directory (expand-file-name "builds/" elpaca-directory))
  (defvar elpaca-sources-directory (expand-file-name "sources/" elpaca-directory))
  (defvar elpaca-order '(elpaca :repo "https://github.com/progfolio/elpaca.git"
                                :ref nil :depth 1 :inherit ignore
                                :files (:defaults "elpaca-test.el" (:exclude "extensions"))
                                :build (:not elpaca-activate)))
  (let* ((repo  (expand-file-name "elpaca/" elpaca-sources-directory))
         (build (expand-file-name "elpaca/" elpaca-builds-directory))
         (order (cdr elpaca-order))
         (default-directory repo))
    (add-to-list 'load-path (if (file-exists-p build) build repo))
    (unless (file-exists-p repo)
      (make-directory repo t)
      (when (<= emacs-major-version 28) (require 'subr-x))
      (condition-case-unless-debug err
          (if-let* ((buffer (pop-to-buffer-same-window "*elpaca-bootstrap*"))
                    ((zerop (apply #'call-process `("git" nil ,buffer t "clone"
                                                    ,@(when-let* ((depth (plist-get order :depth)))
                                                        (list (format "--depth=%d" depth) "--no-single-branch"))
                                                    ,(plist-get order :repo) ,repo))))
                    ((zerop (call-process "git" nil buffer t "checkout"
                                          (or (plist-get order :ref) "--"))))
                    (emacs (concat invocation-directory invocation-name))
                    ((zerop (call-process emacs nil buffer nil "-Q" "-L" "." "--batch"
                                          "--eval" "(byte-recompile-directory \".\" 0 'force)")))
                    ((require 'elpaca))
                    ((elpaca-generate-autoloads "elpaca" repo)))
              (progn (message "%s" (buffer-string)) (kill-buffer buffer))
            (error "%s" (with-current-buffer buffer (buffer-string))))
        ((error) (warn "%s" err) (delete-directory repo 'recursive))))
    (unless (require 'elpaca-autoloads nil t)
      (require 'elpaca)
      (elpaca-generate-autoloads "elpaca" repo)
      (let ((load-source-file-function nil)) (load "./elpaca-autoloads"))))
  (add-hook 'after-init-hook #'elpaca-process-queues)
  (elpaca `(,@elpaca-order))

  (elpaca elpaca-use-package
    ;; Enable use-package :ensure support for Elpaca.
    (elpaca-use-package-mode))
#+end_src

#+begin_src emacs-lisp
(use-package delsel
  :ensure nil
  :hook (after-init . delete-selection-mode))  
#+end_src

#+begin_src emacs-lisp
(defun ll/keyboard-quit-dwim ()
  "Do-What-I-Mean behaviour for a general `keyboard-quit'.

The generic `keyboard-quit' does not do the expected thing when
the minibuffer is open.  Whereas we want it to close the
minibuffer, even without explicitly focusing it.

The DWIM behaviour of this command is as follows:

- When the region is active, disable it.
- When a minibuffer is open, but not focused, close the minibuffer.
- When the Completions buffer is selected, close it.
- In every other case use the regular `keyboard-quit'."
  (interactive)
  (cond
   ((region-active-p)
    (keyboard-quit))
   ((derived-mode-p 'completion-list-mode)
    (delete-completion-window))
   ((> (minibuffer-depth) 0)
    (abort-recursive-edit))
   (t
    (keyboard-quit))))

(define-key global-map (kbd "C-g") #'ll/keyboard-quit-dwim)

#+end_src

* Basic UI tweaks
#+begin_src emacs-lisp
  (setq inhibit-startup-message t)
  (menu-bar-mode -1)
  (tool-bar-mode -1)
  (scroll-bar-mode -1)
  (setq visible-bell nil)
#+end_src

* Recentf
Log and retrieve most recent files
#+begin_src emacs-lisp
(use-package recentf
  :init
  (recentf-mode 1)
  (setq recentf-max-menu-items 50))  ;; adjust the number of recent files
#+end_src
* Embark
Embark provides a powerful contextual action menu for Emacs, allowing
you to perform various operations on completion candidates and other items.
It extends the capabilities of completion frameworks by offering direct
actions on the candidates.
Just `<leader> .' over any text, explore it :)
#+begin_src emacs-lisp
(use-package embark
  :ensure t
  :defer t)
#+end_src

* Embark-Consult

Embark-Consult provides a bridge between Embark and Consult, ensuring
that Consult commands, like previews, are available when using Embark.
#+begin_src emacs-lisp
(use-package embark-consult
  :ensure t
  :hook
  (embark-collect-mode . consult-preview-at-point-mode)) ;; Enable preview in Embark collect mode.
#+end_src

* Package management
#+begin_src emacs-lisp
  ;; Example packages managed by Elpaca

  (use-package magit
    :ensure t
    :defer t)

  (use-package vertico
    :ensure t
    :init (vertico-mode))


  (use-package orderless
    :ensure t
    :after vertico
    :custom (completion-styles '(orderless basic)))

  (use-package marginalia
    :ensure t
    :init (marginalia-mode))
#+end_src

* Exploring Filesystem

** Vertico extension
This package is a Vertico extension, which provides Ido-like
directory navigation commands.  The commands can be bound in the
~vertico-map~.
#+begin_src emacs-lisp
(use-package vertico-directory
    :after vertico
    :ensure nil
    ;; More convenient directory navigation commands
    :bind (:map vertico-map
                ("RET" . vertico-directory-enter)
                ("DEL" . vertico-directory-delete-char)
                ("M-DEL" . vertico-directory-delete-word))
    ;; Tidy shadowed file names
    :hook (rfn-eshadow-update-overlay . vertico-directory-tidy))
#+end_src

* Consult
Consult provides powerful completion and narrowing commands for Emacs.
It integrates well with other completion frameworks like Vertico, enabling
features like previews and enhanced register management. It's useful for
navigating buffers, files, and xrefs with ease.

#+begin_src emacs-lisp
   (use-package consult
     :ensure t
     :defer t
     :init
     ;; Enhance register preview with thin lines and no mode line.
     (advice-add #'register-preview :override #'consult-register-window)

     ;; Use Consult for xref locations with a preview feature.
     (setq xref-show-xrefs-function #'consult-xref
           xref-show-definitions-function #'consult-xref))

#+end_src

#+begin_src emacs-lisp
(defun ll/consult-project-or-all-buffers ()
  "Use `consult-project-buffer' if in a project, else `consult-buffer'."
  (interactive)
  (if (project-current)
      (consult-project-buffer)
    (consult-buffer)))
#+end_src

* Treesitter
Treesit-auto simplifies the use of Tree-sitter grammars in Emacs,
providing automatic installation and mode association for various
programming languages. This enhances syntax highlighting and
code parsing capabilities, making it easier to work with modern
programming languages.

#+begin_src emacs-lisp
(use-package treesit-auto
  :ensure t
  ;; :after emacs
  :custom
  (treesit-auto-install 'prompt)
  :config
  (treesit-auto-add-to-auto-mode-alist 'all)
  (global-treesit-auto-mode t))
#+end_src

* Org Mode setup
#+begin_src emacs-lisp
(use-package org
  :ensure nil
  :config
  (setq org-startup-indented t
        org-hide-emphasis-markers t))
#+end_src

* Appearance
** Font
#+begin_src emacs-lisp
(set-face-attribute 'default nil :font "JetBrainsMono Nerd Font 16")
#+end_src

** Theme 
#+begin_src emacs-lisp
  (use-package modus-themes
      :ensure t
      :init
      (load-theme 'modus-vivendi-tinted t))
#+end_src

** Modeline
#+begin_src emacs-lisp
  (use-package doom-modeline
      :ensure t
      :defer t
      :custom
      (doom-modeline-buffer-file-name-style 'buffer-name)  ;; Set the buffer file name style to just the buffer name (without path).
      (doom-modeline-project-detection 'project)           ;; Enable project detection for displaying the project name.
      (doom-modeline-buffer-name t)                        ;; Show the buffer name in the mode line.
      (doom-modeline-vcs-max-length 25)                    ;; Limit the version control system (VCS) branch name length to 25 characters.
      :config
      (if ll/use-nerd-fonts                                ;; Check if nerd fonts are being used.
          (setq doom-modeline-icon t)                      ;; Enable icons in the mode line if nerd fonts are used.
          (setq doom-modeline-icon nil))                     ;; Disable icons if nerd fonts are not being used.
      :init
      (doom-modeline-mode 1))
#+end_src

** Nerd Icons
The `nerd-icons' package provides a set of icons for use in Emacs. These icons can
enhance the visual appearance of various modes and packages, making it easier to
distinguish between different file types and functionalities.

#+begin_src emacs-lisp
(use-package nerd-icons
:if ll/use-nerd-fonts
:ensure t
:defer t)
#+end_src

** Nerd Icons Dired
The `nerd-icons-dired' package integrates nerd icons into the Dired mode,
providing visual icons for files and directories. This enhances the Dired
interface by making it easier to identify file types at a glance.

#+begin_src emacs-lisp
(use-package nerd-icons-dired
:if ll/use-nerd-fonts                   ;; Load the package only if the user has configured to use nerd fonts.
:ensure t                               ;; Ensure the package is installed.
:defer t                                ;; Load the package only when needed to improve startup time.
:hook
(dired-mode . nerd-icons-dired-mode))
#+end_src

** Nerd Icons Completion
The `nerd-icons-completion' package enhances the completion interfaces in
Emacs by integrating nerd icons with completion frameworks such as
`marginalia'. This provides visual cues for the completion candidates,
making it easier to distinguish between different types of items.

#+begin_src emacs-lisp
(use-package nerd-icons-completion
:if ll/use-nerd-fonts                   ;; Load the package only if the user has configured to use nerd fonts.
:ensure t                               ;; Ensure the package is installed.
:after (:all nerd-icons marginalia)     ;; Load after `nerd-icons' and `marginalia' to ensure proper integration.
:config
(nerd-icons-completion-mode)            ;; Activate nerd icons for completion interfaces.
(add-hook 'marginalia-mode-hook #'nerd-icons-completion-marginalia-setup)) ;; Setup icons in the marginalia mode for enhanced completion display.
#+end_src
* Auto-completion
#+begin_src emacs-lisp
  (use-package company
    :ensure t
    :hook ((after-init . global-company-mode)
  	 (lsp-mode . company-mode))
    :config
    ;; optional tweaks
    (setq company-idle-delay 0.2        ;; how quickly completions pop up
          company-minimum-prefix-length 1
          company-selection-wrap-around t))
#+end_src

* Editing enhancements

#+begin_src emacs-lisp
(use-package which-key
  :ensure t
  :init (which-key-mode))
#+end_src

* Undo-tree
The `undo-tree' package provides an advanced and visual way to
manage undo history. It allows you to navigate and visualize your
undo history as a tree structure, making it easier to manage
changes in your buffers.

#+begin_src emacs-lisp
  (use-package undo-tree
    :defer t
    :ensure t
    :init
    (setq undo-tree-visualizer-timestamps t
          undo-tree-visualizer-diff t
          ;; Increase undo limits to avoid losing history due to Emacs' garbage collection.
          ;; These values can be adjusted based on your needs.
          ;; 10X bump of the undo limits to avoid issues with premature
          ;; Emacs GC which truncates the undo history very aggressively.
          undo-limit 800000                     ;; Limit for undo entries.
          undo-strong-limit 12000000            ;; Strong limit for undo entries.
          undo-outer-limit 120000000)           ;; Outer limit for undo entries.
    (global-undo-tree-mode)
    :config
    ;; Set the directory where `undo-tree' will save its history files.
    ;; This keeps undo history across sessions, stored in a cache directory.
    (setq undo-tree-history-directory-alist '(("." . "~/config/emacs/.cache/undo"))))
#+end_src


* LSP
#+begin_src emacs-lisp
    (use-package lsp-mode
    :init
    ;; set prefix for lsp-command-keymap (few alternatives - "C-l", "C-c l")
    (setq lsp-keymap-prefix "C-c l")
    :hook (;; replace XXX-mode with concrete major-mode(e. g. python-mode)
           (XXX-mode . lsp)
           ;; if you want which-key integration
           (lsp-mode . lsp-enable-which-key-integration))
    :commands lsp)

  ;; optionally
  (use-package lsp-ui :commands lsp-ui-mode)
  ;; if you are helm user
  (use-package helm-lsp :commands helm-lsp-workspace-symbol)
  ;; if you are ivy user
  (use-package lsp-ivy :commands lsp-ivy-workspace-symbol)
  (use-package lsp-treemacs :commands lsp-treemacs-errors-list)
#+end_src

* Python

** Breakpoints

Bindings and functions to add and highlight breakpoints.
#+begin_src emacs-lisp :tangle yes
(defvar python--pdb-breakpoint-string "breakpoint()")
(defun ll/python-add-breakpoint ()
"Inserts a python breakpoint using `pdb'"
    (interactive)
    (back-to-indentation)
    ;; this preserves the correct indentation in case the line above
    ;; point is a nested block
    (split-line)
    (insert python--pdb-breakpoint-string)
    (python-set-debug-highlight))

(defun python-set-debug-highlight ()
    (interactive)
    (highlight-lines-matching-regexp "breakpoint[.]?" 'hi-red-b))
#+end_src

#+begin_src emacs-lisp
(add-hook 'python-ts-mode-hook
          (lambda ()
            (define-key python-ts-mode-map (kbd "<leader> m d") 'll/python-add-breakpoint)))
#+end_src

* Direnv
Direnv works by invoking direnv to obtain the environment for the current file, then updating the emacs
variables process-environment and exec-path.

The result is that programs started from within emacs, such as inferior shells, linters,
compilers, and test runners, will be looked up in the correct $PATH, and will be started with the correct environment variables set.

* Org-mode
#+begin_src emacs-lisp
  (use-package org
    :ensure nil  ;; Don't install org from ELPA, use the built-in one
    :config
    (define-key org-mode-map (kbd "<leader> m e") #'org-export-dispatch))
#+end_src

* Window Management

#+begin_src emacs-lisp :tangle yes
  (winner-mode)
  (defun toggle-maximize-window ()
   "Maximize the window or bring back the previous layout."
    (interactive)
    (if (one-window-p)
      (winner-undo)
      (delete-other-windows)))
#+end_src


